#cloud-config
timezone: Asia/Tokyo

users:
  - name: shishi
    primary_group: shishi
    groups: [adm, audio, cdrom, dialout, floppy, video, plugdev, dip, netdev, sudo, lxd]
    homedir: /home/shishi
    shell: /usr/bin/bash
    ssh_import_id: gh:shishi
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - mkdir -p /home/shishi/.local/bin
  - curl -L https://github.com/itamae-kitchen/mitamae/releases/latest/download/mitamae-x86_64-linux.tar.gz | tar xvz
  - mv ./mitamae-x86_64-linux /home/shishi/.local/bin/mitamae
  - chown -R shishi:shishi /home/shishi/.local/
